// ODIN Mobile — Upcoming Catalyst Data
// Extracted from pdufa.bio scoring engine

import { Catalyst } from './types';

export const CATALYSTS_DATA: Catalyst[] = [
  {
    id: 'vnda-bysanti-2026-02-21',
    date: '2026-02-21',
    company: 'Vanda Pharmaceuticals',
    ticker: 'VNDA',
    drug: 'Bysanti (milsaperidone)',
    indication: 'Schizophrenia / Bipolar-I',
    type: 'PDUFA',
    appType: 'NDA',
    ta: 'CNS',
    phase: 'Phase 3',
    designations: [],
    prob: 0.3959,
    tier: 'TIER_4',
    signals: {
      'inexperienced_sponsor': -1.2875,
      'ta_mod_risk': -0.1809,
      'me_too': -0.35
    },
  },
  {
    id: 'otsuka-inqovi-venetoclax-2026-02-25',
    date: '2026-02-25',
    company: 'Otsuka',
    ticker: 'OTSKF',
    drug: 'INQOVI + Venetoclax',
    indication: 'Acute Myeloid Leukemia',
    type: 'PDUFA',
    appType: 'sNDA',
    ta: 'Oncology',
    phase: 'Phase 3',
    designations: [],
    prob: 0.8556,
    tier: 'TIER_1',
    signals: {
      'sNDA/sBLA': -0.441,
      'experienced_sponsor': 0.9387,
      'ta_low_risk': 0.0838,
      'ind_cancer': 0.2523,
      'single_arm_pivotal': -0.55,
      'division_favorable': 0.1
    },
  },
  {
    id: 'regn-dupixent-afrs-2026-02-28',
    date: '2026-02-28',
    company: 'Regeneron / Sanofi',
    ticker: 'REGN',
    drug: 'Dupixent',
    indication: 'Allergic Fungal Rhinosinusitis',
    type: 'PDUFA',
    appType: 'sBLA',
    ta: 'Immunology',
    phase: 'Phase 3',
    designations: ['Priority Review'],
    prob: 0.9304,
    tier: 'TIER_1',
    signals: {
      'sNDA/sBLA': -0.441,
      'priority_review': 0.615,
      'experienced_sponsor': 0.9387,
      'ta_low_risk': 0.0838
    },
  },
  {
    id: 'asnd-navepegritide-2026-02-28',
    date: '2026-02-28',
    company: 'Ascendis Pharma',
    ticker: 'ASND',
    drug: 'Navepegritide (TransCon CNP)',
    indication: 'Achondroplasia',
    type: 'PDUFA',
    appType: 'BLA',
    ta: 'Rare Disease',
    phase: 'Phase 3',
    designations: ['Orphan Drug', 'Priority Review'],
    prob: 0.9554,
    tier: 'TIER_1',
    signals: {
      'experienced_sponsor': 0.9387,
      'orphan': 0.1469,
      'priority_review': 0.615,
      'primary_endpoint_met': 0.45,
      'ta_mod_risk': -0.1809,
      'me_too': -0.35,
      'pdufa_extension': -0.15,
      'fda_no_adcom_required': 0.2
    },
  },
  {
    id: 'bmy-deucravacitinib-2026-03-06',
    date: '2026-03-06',
    company: 'Bristol-Myers Squibb',
    ticker: 'BMY',
    drug: 'Deucravacitinib (Sotyktu)',
    indication: 'Psoriatic Arthritis',
    type: 'PDUFA',
    appType: 'sNDA',
    ta: 'Immunology',
    phase: 'Phase 3',
    designations: [],
    prob: 0.8887,
    tier: 'TIER_1',
    signals: {
      'sNDA/sBLA': -0.441,
      'experienced_sponsor': 0.9387,
      'ta_low_risk': 0.0838,
      'division_favorable': 0.1
    },
  },
  {
    id: 'aldx-reproxalap-2026-03-16',
    date: '2026-03-16',
    company: 'Aldeyra Therapeutics',
    ticker: 'ALDX',
    drug: 'Reproxalap',
    indication: 'Dry Eye Disease',
    type: 'PDUFA',
    appType: 'NDA',
    ta: 'Ophthalmology',
    phase: 'Phase 3',
    designations: [],
    prob: 0.011,
    tier: 'TIER_4',
    signals: {
      'prior_CRL': -3.3533,
      'resubmission_post_CRL': 2.0,
      'serial_crl_penalty': -0.50,
      'inexperienced_sponsor': -1.2875,
      'hist_crl_rate': -1.4953,
      'ta_high_risk': -0.2555,
      'novice_high_risk_ta': -0.4071,
      'surrogate_only': -0.45,
      'me_too': -0.35,
      'fda_no_adcom_required': 0.2
    },
  },
  {
    id: 'rytm-imcivree-2026-03-20',
    date: '2026-03-20',
    company: 'Rhythm Pharmaceuticals',
    ticker: 'RYTM',
    drug: 'Imcivree (setmelanotide)',
    indication: 'Acquired Hypothalamic Obesity',
    type: 'PDUFA',
    appType: 'sNDA',
    ta: 'Metabolic/Endocrine',
    phase: 'Phase 3',
    designations: ['Orphan Drug'],
    prob: 0.5208,
    tier: 'TIER_4',
    signals: {
      'sNDA/sBLA': -0.441,
      'inexperienced_sponsor': -1.2875,
      'orphan': 0.1469,
      'ta_mod_risk': -0.1809,
      'first_in_class': 0.45
    },
  },
  {
    id: 'gsk-linerixibat-2026-03-24',
    date: '2026-03-24',
    company: 'GSK',
    ticker: 'GSK',
    drug: 'Linerixibat',
    indication: 'Cholestatic Pruritus (PBC)',
    type: 'PDUFA',
    appType: 'NDA',
    ta: 'GI/Hepatology',
    phase: 'Phase 3',
    designations: [],
    prob: 0.9656,
    tier: 'TIER_1',
    signals: {
      'experienced_sponsor': 0.9387,
      'first_in_class': 0.45,
      'unmet_need': 0.55
    },
  },
  {
    id: 'lly-orforglipron-2026-03-25',
    date: '2026-03-25',
    company: 'Eli Lilly',
    ticker: 'LLY',
    drug: 'Orforglipron',
    indication: 'Type 2 Diabetes / Obesity',
    type: 'PDUFA (Expected)',
    appType: 'NDA',
    ta: 'Metabolic/Endocrine',
    phase: 'Phase 3',
    designations: ['National Priority Voucher'],
    prob: 0.9615,
    tier: 'TIER_1',
    signals: {
      'priority_review': 0.615,
      'experienced_sponsor': 0.9387,
      'ta_mod_risk': -0.1809,
      'first_in_class': 0.45
    },
  },
  {
    id: 'iron-bitopertin-2026-03-25b',
    date: '2026-03-25',
    company: 'Disc Medicine',
    ticker: 'IRON',
    drug: 'Bitopertin',
    indication: 'Erythropoietic Protoporphyria',
    type: 'PDUFA (Expected)',
    appType: 'NDA',
    ta: 'Hematology',
    phase: 'Phase 3',
    designations: ['Orphan Drug', 'Breakthrough Therapy'],
    prob: 0.3573,
    tier: 'TIER_4',
    signals: {
      'inexperienced_sponsor': -1.2875,
      'BTD': 0.1676,
      'orphan': 0.1469,
      'ta_high_risk': -0.2555,
      'novice_high_risk_ta': -0.4071,
      'surrogate_only': -0.45,
      'first_in_class': 0.45,
      'unmet_need': 0.55,
      'designation_stack': 0.35,
      'accelerated_approval_non_onc': -0.30,
      'surrogate_clinical_disconnect': -0.35,
      'designation_surrogate_penalty': -0.25,
      'repurposed_failed_compound': -0.20,
      'early_action_risk': -0.15
    },
  },
  {
    id: 'rckt-kresladi-2026-03-28',
    date: '2026-03-28',
    company: 'Rocket Pharmaceuticals',
    ticker: 'RCKT',
    drug: 'Kresladi (marnetegragene autotemcel)',
    indication: 'Leukocyte Adhesion Deficiency-I',
    type: 'PDUFA',
    appType: 'BLA',
    ta: 'Rare Disease',
    phase: 'Phase 1/2',
    designations: ['Orphan Drug', 'Breakthrough Therapy', 'Priority Review'],
    prob: 0.3088,
    tier: 'TIER_4',
    signals: {
      'inexperienced_sponsor': -1.2875,
      'BTD': 0.1676,
      'orphan': 0.1469,
      'priority_review': 0.615,
      'class1_resub': 0.57,
      'manufacturing_risk': -1.0589,
      'cmc_extension': -0.9845,
      'single_arm_pivotal': -0.55,
      'small_pivotal_n': -0.4,
      'first_in_class': 0.45,
      'unmet_need': 0.55,
      'interaction_inexperienced_mfg': -0.5,
      'cber_advanced_therapy': -0.12,
      'social_positive': 0.2
    },
  },
  {
    id: 'lnth-ga68-edotreotide-2026-03-29',
    date: '2026-03-29',
    company: 'Lantheus',
    ticker: 'LNTH',
    drug: 'Gallium-68 edotreotide',
    indication: 'NET PET Imaging',
    type: 'PDUFA',
    appType: 'NDA',
    ta: 'Oncology',
    phase: 'Phase 3',
    designations: [],
    prob: 0.8291,
    tier: 'TIER_2',
    signals: {
      'ta_low_risk': 0.0838,
      'division_favorable': 0.1
    },
  },
  {
    id: 'dnli-tividenofusp-2026-04-05',
    date: '2026-04-05',
    company: 'Denali Therapeutics',
    ticker: 'DNLI',
    drug: 'Tividenofusp alfa',
    indication: 'Hunter Syndrome (MPS II)',
    type: 'PDUFA',
    appType: 'BLA',
    ta: 'Rare Disease',
    phase: 'Phase 2/3',
    designations: ['Breakthrough Therapy', 'Orphan Drug', 'Priority Review'],
    prob: 0.1383,
    tier: 'TIER_4',
    signals: {
      'inexperienced_sponsor': -1.2875,
      'BTD': 0.1676,
      'orphan': 0.1469,
      'priority_review': 0.615,
      'cmc_extension': -0.9845,
      's22_pediatric_pk': -1.9328,
      'surrogate_only': -0.45,
      'first_in_class': 0.45,
      'unmet_need': 0.55,
      'interaction_inexperienced_mfg': -0.5
    },
  },
  {
    id: 'orca-orca-t-2026-04-06',
    date: '2026-04-06',
    company: 'Orca Bio',
    ticker: 'ORCA',
    drug: 'Orca-T',
    indication: 'Hematologic Malignancies (AML/ALL/MDS)',
    type: 'PDUFA',
    appType: 'BLA',
    ta: 'Oncology',
    phase: 'Phase 3',
    designations: ['Priority Review'],
    prob: 0.8438,
    tier: 'TIER_2',
    signals: {
      'inexperienced_sponsor': -1.2875,
      'priority_review': 0.615,
      'ta_low_risk': 0.0838,
      'first_in_class': 0.45,
      'unmet_need': 0.55,
      'cber_advanced_therapy': -0.12
    },
  },
  {
    id: 'tvtx-sparsentan-2026-04-13',
    date: '2026-04-13',
    company: 'Travere Therapeutics',
    ticker: 'TVTX',
    drug: 'Sparsentan',
    indication: 'Focal Segmental Glomerulosclerosis (FSGS)',
    type: 'PDUFA',
    appType: 'sNDA',
    ta: 'Nephrology',
    phase: 'Phase 3',
    designations: ['Priority Review', 'Accelerated Approval conversion'],
    prob: 0.1115,
    tier: 'TIER_4',
    signals: {
      'sNDA/sBLA': -0.441,
      'inexperienced_sponsor': -1.2875,
      'priority_review': 0.615,
      'accel_approval': 0.5552,
      'ta_high_risk': -0.2555,
      'novice_high_risk_ta': -0.4071,
      'primary_endpoint_missed': -1.8,
      'surrogate_only': -0.45
    },
  },
  {
    id: 'azn-baxdrostat-2026-05-15',
    date: '2026-05-15',
    company: 'AstraZeneca',
    ticker: 'AZN',
    drug: 'Baxdrostat',
    indication: 'Treatment-Resistant Hypertension',
    type: 'PDUFA (Expected)',
    appType: 'NDA',
    ta: 'Cardiovascular',
    phase: 'Phase 3',
    designations: ['Priority Review'],
    prob: 0.9615,
    tier: 'TIER_1',
    signals: {
      'priority_review': 0.615,
      'experienced_sponsor': 0.9387,
      'ta_mod_risk': -0.1809,
      'first_in_class': 0.45
    },
  },
  {
    id: 'aclx-cytisinicline-2026-06-20',
    date: '2026-06-20',
    company: 'Achieve Life Sciences',
    ticker: 'ACHV',
    drug: 'Cytisinicline',
    indication: 'Smoking Cessation',
    type: 'PDUFA',
    appType: 'NDA',
    ta: 'CNS',
    phase: 'Phase 3',
    designations: ['Breakthrough Therapy'],
    prob: 0.3522,
    tier: 'TIER_4',
    signals: {
      'inexperienced_sponsor': -1.2875,
      'BTD': 0.1676,
      'ta_mod_risk': -0.1809,
      'indication_pain': -0.3546,
      'me_too': -0.35
    },
  },
  {
    id: 'vrdn-veligrotug-2026-06-30',
    date: '2026-06-30',
    company: 'Viridian Therapeutics',
    ticker: 'VRDN',
    drug: 'Veligrotug',
    indication: 'Thyroid Eye Disease',
    type: 'PDUFA',
    appType: 'BLA',
    ta: 'Immunology',
    phase: 'Phase 3',
    designations: ['Priority Review'],
    prob: 0.7785,
    tier: 'TIER_2',
    signals: {
      'inexperienced_sponsor': -1.2875,
      'priority_review': 0.615,
      'ta_low_risk': 0.0838,
      'first_in_class': 0.45
    },
  },
  {
    id: 'kura-tipifarnib-2026-07-01',
    date: '2026-07-01',
    company: 'Kura Oncology',
    ticker: 'KURA',
    drug: 'Tipifarnib',
    indication: 'HRAS-mutant HNSCC',
    type: 'PDUFA',
    appType: 'NDA',
    ta: 'Oncology',
    phase: 'Phase 2',
    designations: ['Breakthrough Therapy', 'Orphan Drug', 'Priority Review'],
    prob: 0.9022,
    tier: 'TIER_1',
    signals: {
      'inexperienced_sponsor': -1.2875,
      'BTD': 0.1676,
      'orphan': 0.1469,
      'priority_review': 0.615,
      'ta_low_risk': 0.0838,
      'first_in_class': 0.45,
      'unmet_need': 0.55,
      'division_favorable': 0.1
    },
  },
  {
    id: 'gsk-varicella-vaccine-2026-07-01',
    date: '2026-07-01',
    company: 'GSK',
    ticker: 'GSK',
    drug: 'Varicella vaccine (investigational)',
    indication: 'Chickenpox',
    type: 'READOUT',
    appType: '',
    ta: 'Vaccines',
    phase: 'Phase 3',
    designations: [],
    prob: 0.9194,
    tier: 'TIER_1',
    signals: {
      'experienced_sponsor': 0.9387,
      'division_favorable': 0.1
    },
  },
  {
    id: 'mrk-pembrolizumab-combos-2026-07-06',
    date: '2026-07-06',
    company: 'Merck',
    ticker: 'MRK',
    drug: 'Pembrolizumab combos',
    indication: 'Lung Cancer (multiple trials)',
    type: 'READOUT',
    appType: '',
    ta: 'Oncology',
    phase: 'Phase 3',
    designations: [],
    prob: 0.9411,
    tier: 'TIER_1',
    signals: {
      'experienced_sponsor': 0.9387,
      'ta_low_risk': 0.0838,
      'ind_cancer': 0.2523,
      'division_favorable': 0.1
    },
  },
  {
    id: 'vera-atacicept-2026-07-07',
    date: '2026-07-07',
    company: 'Vera Therapeutics',
    ticker: 'VERA',
    drug: 'Atacicept',
    indication: 'IgA Nephropathy',
    type: 'PDUFA',
    appType: 'BLA',
    ta: 'Nephrology',
    phase: 'Phase 3',
    designations: ['Breakthrough Therapy', 'Orphan Drug'],
    prob: 0.7232,
    tier: 'TIER_2',
    signals: {
      'inexperienced_sponsor': -1.2875,
      'BTD': 0.1676,
      'orphan': 0.1469,
      'ta_high_risk': -0.2555,
      'novice_high_risk_ta': -0.4071,
      'first_in_class': 0.45,
      'unmet_need': 0.55,
      'social_positive': 0.2
    },
  },
  {
    id: 'regn-mibavademab-2026-07-14',
    date: '2026-07-14',
    company: 'Regeneron',
    ticker: 'REGN',
    drug: 'Mibavademab',
    indication: 'Generalized Lipodystrophy',
    type: 'READOUT',
    appType: '',
    ta: 'Rare Disease',
    phase: 'Phase 3',
    designations: [],
    prob: 0.9117,
    tier: 'TIER_1',
    signals: {
      'experienced_sponsor': 0.9387
    },
  },
  {
    id: 'azn-tezepelumab-2026-07-14',
    date: '2026-07-14',
    company: 'AstraZeneca',
    ticker: 'AZN',
    drug: 'Tezepelumab',
    indication: 'Eosinophilic Esophagitis',
    type: 'READOUT',
    appType: '',
    ta: 'GI/Hepatology',
    phase: 'Phase 3',
    designations: [],
    prob: 0.9117,
    tier: 'TIER_1',
    signals: {
      'experienced_sponsor': 0.9387
    },
  },
  {
    id: 'lly-lebrikizumab-2026-07-15',
    date: '2026-07-15',
    company: 'Eli Lilly',
    ticker: 'LLY',
    drug: 'Lebrikizumab',
    indication: 'Atopic Hand/Foot Dermatitis',
    type: 'READOUT',
    appType: '',
    ta: 'Dermatology',
    phase: 'Phase 3',
    designations: [],
    prob: 0.9254,
    tier: 'TIER_1',
    signals: {
      'experienced_sponsor': 0.9387,
      'ta_low_risk': 0.0838,
      'division_favorable': 0.1
    },
  },
  {
    id: 'hrmy-pitolisant-2026-07-15',
    date: '2026-07-15',
    company: 'Harmony Biosciences',
    ticker: 'HRMY',
    drug: 'Pitolisant',
    indication: 'Prader-Willi Syndrome',
    type: 'READOUT',
    appType: '',
    ta: 'CNS',
    phase: 'Phase 3',
    designations: [],
    prob: 0.0443,
    tier: 'TIER_4',
    signals: {
      'inexperienced_sponsor': -1.2875,
      'ta_mod_risk': -0.1809,
      'refused_to_file': -1.2,
      'primary_endpoint_missed': -1.8
    },
  },
  {
    id: 'lxrx-sotagliflozin-2026-07-15',
    date: '2026-07-15',
    company: 'Lexicon Pharmaceuticals',
    ticker: 'LXRX',
    drug: 'Sotagliflozin',
    indication: 'Hypertrophic Obstructive Cardiomyopathy',
    type: 'READOUT',
    appType: '',
    ta: 'Cardiovascular',
    phase: 'Phase 3',
    designations: [],
    prob: 0.5069,
    tier: 'TIER_4',
    signals: {
      'inexperienced_sponsor': -1.2875,
      'ta_mod_risk': -0.1809,
      'first_in_class': 0.45,
      'me_too': -0.35
    },
  },
  {
    id: 'rare-gtx-102-2026-07-15',
    date: '2026-07-15',
    company: 'Ultragenyx',
    ticker: 'RARE',
    drug: 'GTX-102',
    indication: 'Angelman Syndrome',
    type: 'READOUT',
    appType: '',
    ta: 'Rare Disease',
    phase: 'Phase 3',
    designations: [],
    prob: 0.7922,
    tier: 'TIER_2',
    signals: {
      'inexperienced_sponsor': -1.2875,
      'first_in_class': 0.45,
      'unmet_need': 0.55,
      'designation_stack': 0.35,
      'cber_advanced_therapy': -0.12
    },
  },
  {
    id: 'vrdn-vrdn-003-2026-07-15',
    date: '2026-07-15',
    company: 'Viridian Therapeutics',
    ticker: 'VRDN',
    drug: 'VRDN-003',
    indication: 'Thyroid Eye Disease',
    type: 'READOUT',
    appType: '',
    ta: 'Immunology',
    phase: 'Phase 3',
    designations: [],
    prob: 0.5725,
    tier: 'TIER_4',
    signals: {
      'inexperienced_sponsor': -1.2875,
      'ta_low_risk': 0.0838,
      'division_favorable': 0.1
    },
  },
  {
    id: 'mrk-tulisokibart-2026-08-01',
    date: '2026-08-01',
    company: 'Merck',
    ticker: 'MRK',
    drug: 'Tulisokibart (IV+SC)',
    indication: 'Ulcerative Colitis',
    type: 'READOUT',
    appType: '',
    ta: 'GI/Hepatology',
    phase: 'Phase 3',
    designations: [],
    prob: 0.9117,
    tier: 'TIER_1',
    signals: {
      'experienced_sponsor': 0.9387
    },
  },
];
